# Generated by Django 4.2.3 on 2023-07-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Struttura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('fondazione', models.DateField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('long', models.FloatField(null=True)),
                ('dimensione', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('spogliatoi', models.BooleanField(default=False)),
            ],
        ),
    ]
