# Generated by Django 4.2.3 on 2023-08-13 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Struttura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('fondazione', models.DateField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('long', models.FloatField(null=True)),
                ('dimensione', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('spogliatoi', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdminStruttura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('struttura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='struttura.struttura')),
            ],
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('num_campo', models.PositiveSmallIntegerField()),
                ('costo_orario', models.DecimalField(decimal_places=1, max_digits=3)),
                ('coperto', models.BooleanField(null=True)),
                ('illuminato', models.BooleanField(null=True)),
                ('tipo_superficie', models.CharField(choices=[('sintetico', 'sintetico'), ('naturale', 'naturale'), ('parquet', 'parquet'), ('cemento', 'cemento'), ('palestra', 'palestra')], max_length=9, null=True)),
                ('struttura', models.ForeignKey(db_column='struttura', on_delete=django.db.models.deletion.CASCADE, to='struttura.struttura')),
            ],
            options={
                'unique_together': {('struttura', 'num_campo')},
            },
        ),
    ]
