# Generated by Django 4.2.3 on 2023-08-01 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('struttura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('struttura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='struttura.struttura')),
                ('num_campo', models.PositiveSmallIntegerField()),
                ('costo_orario', models.DecimalField(decimal_places=1, max_digits=3)),
                ('coperto', models.BooleanField(null=True)),
                ('illuminato', models.BooleanField(null=True)),
                ('tipo_superficie', models.TextField(choices=[('sintetico', 'Sintetico'), ('naturale', 'Naturale'), ('parquet', 'Parquet'), ('cemento', 'Cemento'), ('palestra', 'Palestra')], null=True)),
            ],
            options={
                'unique_together': {('struttura', 'num_campo')},
            },
        ),
    ]
