# Generated by Django 4.2.3 on 2023-08-13 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('struttura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField(choices=[(1, 'Uno'), (2, 'Due'), (3, 'Tre'), (4, 'Quattro'), (5, 'Cinque')])),
                ('descrizione', models.CharField(max_length=200, null=True)),
                ('struttura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='struttura.struttura')),
                ('votante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('votante', 'struttura')},
            },
        ),
    ]
