# Generated by Django 4.2.3 on 2023-08-01 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('struttura', '0002_campo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='struttura',
            field=models.OneToOneField(db_column='struttura', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='struttura.struttura'),
        ),
    ]
