# Generated by Django 4.2.3 on 2023-08-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struttura', '0003_alter_campo_struttura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='tipo_superficie',
            field=models.TextField(choices=[('sintetico', 'sintetico'), ('naturale', 'naturale'), ('parquet', 'parquet'), ('cemento', 'cemento'), ('palestra', 'palestra')], null=True),
        ),
    ]
