# Generated by Django 4.2.3 on 2023-08-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struttura', '0004_alter_campo_tipo_superficie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='tipo_superficie',
            field=models.CharField(choices=[('sintetico', 'sintetico'), ('naturale', 'naturale'), ('parquet', 'parquet'), ('cemento', 'cemento'), ('palestra', 'palestra')], max_length=9, null=True),
        ),
    ]
