# Generated by Django 4.2.3 on 2023-08-01 14:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('struttura', '0006_adminstruttura_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminStruttura',
            new_name='Prenotazione',
        ),
    ]
