# Generated by Django 4.2.3 on 2023-08-01 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('struttura', '0007_rename_adminstruttura_prenotazione'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminStruttura',
            fields=[
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('struttura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='struttura.struttura')),
            ],
            options={
                'unique_together': {('admin', 'struttura')},
            },
        ),
    ]
