# Generated by Django 4.2.3 on 2023-08-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('struttura', '0010_remove_adminstruttura_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adminstruttura',
            unique_together=set(),
        ),
    ]
