# Generated by Django 4.2.3 on 2023-08-01 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('struttura', '0011_alter_adminstruttura_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminstruttura',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminstruttura',
            name='struttura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='struttura.struttura'),
        ),
    ]
