# Generated by Django 4.2.3 on 2023-07-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0002_alter_avatarutente_img_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posizionigioco',
            name='alternativa',
            field=models.CharField(choices=[('POR', 'Portiere'), ('DIF', 'Difensore'), ('CEN', 'Centrocampista'), ('ATT', 'Attaccante'), ('DIF_TER', 'Terzino'), ('CEN_ALA', 'Ala'), ('CEN_TRQ', 'Trequartista'), ('QLS', 'Qualsiasi')], default='QLS', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='posizionigioco',
            name='alternativa2',
            field=models.CharField(choices=[('POR', 'Portiere'), ('DIF', 'Difensore'), ('CEN', 'Centrocampista'), ('ATT', 'Attaccante'), ('DIF_TER', 'Terzino'), ('CEN_ALA', 'Ala'), ('CEN_TRQ', 'Trequartista'), ('QLS', 'Qualsiasi')], default='QLS', max_length=7, null=True),
        ),
    ]
