# Generated by Django 4.2.3 on 2023-07-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0003_alter_posizionigioco_alternativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caratteristichegioco',
            name='secondaria',
            field=models.CharField(choices=[('veloce', 'Veloce'), ('agile', 'Agile'), ('tecnico', 'Tecnico'), ('fisico', 'Fisico'), ('tattico', 'Tattico'), ('acrobata', 'Acrobata')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='caratteristichegioco',
            name='terziaria',
            field=models.CharField(choices=[('veloce', 'Veloce'), ('agile', 'Agile'), ('tecnico', 'Tecnico'), ('fisico', 'Fisico'), ('tattico', 'Tattico'), ('acrobata', 'Acrobata')], max_length=8, null=True),
        ),
    ]
