# Generated by Django 4.2.3 on 2023-08-14 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('struttura', '0002_recensione'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inizio', models.DateTimeField()),
                ('fine', models.DateTimeField()),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='struttura.campo')),
                ('prenotante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='prenotazione',
            constraint=models.CheckConstraint(check=models.Q(('fine__gt', models.F('inizio'))), name='Controllo orari prenotazione'),
        ),
    ]
