# Generated by Django 4.2.3 on 2023-08-08 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('prenotazione', '0001_initial'), ('prenotazione', '0002_alter_prenotazione_unique_together'), ('prenotazione', '0003_alter_prenotazione_unique_together_prenotazione_id_and_more'), ('prenotazione', '0004_rename_num_campo_prenotazione_campo_and_more'), ('prenotazione', '0005_alter_prenotazione_unique_together_and_more'), ('prenotazione', '0006_prenotazione_struttura')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('struttura', '0014_delete_prenotazione'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('prenotante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('inizio', models.DateTimeField()),
                ('fine', models.DateTimeField()),
                ('num_campo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='struttura.campo')),
                ('struttura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='struttura.struttura')),
            ],
        ),
        migrations.AddConstraint(
            model_name='prenotazione',
            constraint=models.CheckConstraint(check=models.Q(('fine__gt', models.F('inizio'))), name='Controllo orari prenotazione'),
        ),
        migrations.AlterUniqueTogether(
            name='prenotazione',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='prenotante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='prenotazione',
            name='struttura',
        ),
        migrations.RenameField(
            model_name='prenotazione',
            old_name='num_campo',
            new_name='campo',
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='struttura',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='struttura.struttura'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='prenotazione',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='prenotazione',
            name='struttura',
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='struttura',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='struttura.struttura'),
            preserve_default=False,
        ),
    ]
