# Generated by Django 4.2.3 on 2023-08-08 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('struttura', '0014_delete_prenotazione'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('prenotante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('inizio', models.DateTimeField()),
                ('fine', models.DateTimeField()),
                ('num_campo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='struttura.campo')),
                ('struttura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='struttura.struttura')),
            ],
        ),
        migrations.AddConstraint(
            model_name='prenotazione',
            constraint=models.CheckConstraint(check=models.Q(('fine__gt', models.F('inizio'))), name='Controllo orari prenotazione'),
        ),
        migrations.AlterUniqueTogether(
            name='prenotazione',
            unique_together={('prenotante', 'struttura'), ('struttura', 'num_campo')},
        ),
    ]
