# Generated by Django 4.2.3 on 2023-08-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('struttura', '0014_delete_prenotazione'),
        ('prenotazione', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prenotazione',
            unique_together={('struttura', 'num_campo')},
        ),
    ]
