# Generated by Django 4.2.3 on 2023-08-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazione', '0004_rename_num_campo_prenotazione_campo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prenotazione',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='prenotazione',
            name='struttura',
        ),
    ]
