# Generated by Django 4.2.3 on 2023-08-08 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazione', '0001_squashed_0006_prenotazione_struttura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenotazione',
            name='struttura',
        ),
    ]
