# Generated by Django 4.2.3 on 2023-08-08 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prenotazione', '0008_alter_prenotazione_campo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='prenotante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
